spring:
  #druid????????pom?????5?
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource  #??????druid
    druid:
       #??springbean
      filters: stat,wall  #???????stat(sql??)?wall(???)

      stat-view-servlet: #???????
        enabled: true
        login-username: admin
        login-password: 123
        reset-enable: false

      web-stat-filter: #??web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter: #???filter???stat????????????
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false  #?????







server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





